apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce # EBS PV provides only ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  awsElasticBlockStore:
    volumeID: vol-05d035a6536a28912 # Static provisioning
    fsType: ext4
