apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 3
  minReadySeconds: 20
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: simpleapp
      labels:
        app: simpleapp
    spec:
      containers:
      - image: zaddyjini/simpleapp:v1
        name: pyapp
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp
spec:
  type: LoadBalancer
  selector:
    app: simpleapp
  ports:
  - port: 80
    targetPort: 8080
