apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 3
  template:
    metadata:
      name: simpleapp
      labels:
        app: simpleapp
    spec:
      containers:
      - image: zaddyjini/simpleapp 
        name: pyapp 
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp
spec:
  type: LoadBalancer
  selector:
    app: simpleapp
  ports:
  - port: 80
    targetPort: 8080
